#!/usr/bin/env python
import sys,os,re

if sys.argv[-1] == "-h" or sys.argv[-1] == "--help":
    print "qstatcmd job-ID ..."
    sys.exit(0)

if len(sys.argv) > 1:
    out = os.popen('qstat').readlines()
    for i in sys.argv[1:]:
        for line in out:
            if i in line:
                print line.strip() + "\n"
                cmd = os.popen('qstat -j %s'%i).read()
                if not re.search('BATCH_JOB_COMMAND=.+?,.+?=:',cmd):
                    print "jobs %s do not exist,"%i ,"orz"
                    break 
                print re.search('BATCH_JOB_COMMAND=(.+?),PERL_LOCAL_LIB_ROOT=:',cmd).group(1) + "\n"
                break
            else:
                continue 
        else:
            print "jobs %s do not exist,"%i ,"orz"

if len(sys.argv) == 1:
    out = os.popen('qstat').readlines()
    for i in out:
        if re.match(" \d+?",i):
            jobid = i.split()[0]
            print i.strip() + "\n"
            cmd = os.popen('qstat -j %s'%jobid).read()
            if not re.search('BATCH_JOB_COMMAND=.+?,.+?=:',cmd):
                print "jobs %s do not exist\n"%jobid
                continue
            print re.search('BATCH_JOB_COMMAND=(.+?),PERL_LOCAL_LIB_ROOT=:',cmd).group(1) + "\n"



